spring.application.name=CostMate

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url= jdbc:h2:file:~/CostMateDB
spring.datasource.username=admin
spring.datasource.password=admin

#JPA config
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


tink.key128Bit=123456789abcdef0
tink.extraKey=12345abcdefg

springdoc.writer-with-default-pretty-printer=true

security.jwt.secret=5c19f8863e7955893c412b7b01d1d6f7dfc38df4a95f486ae7b720c453fa2a6883d9ad1b762ebd93c446d193ddf3480bff1f1647e5eb5a653d56597bf972dbb1
security.jwt.expiration-ms=864000000